# Database settings
mysql:
  use: false
  host: localhost
  port: 3306
  database: database
  username: username
  password: password
  parameters: ?autoReconnect=true&useConfigs=maxPerformance

  # Automatically remove inactive players from the database (remove section to disable)
  purge:
    # How often to check the activity of players? Seconds.
    interval: 7200

    # Check on server startup?
    check-on-startup: true

    # How many days a player must be offline to remove him from the database.
    inactive-days: 30

    # Additional commands that will be executed along with the purge. It may
    # be useful for deleting player data from a databases of other plugins.
    commands: []

top:
  name: '&cNone'
  value: '&cNone'
  excluded:
    - uuid

xp-progress-style:
  xp:
    symbol: \u007c
    color: '&2'
  none:
    symbol: \u007c
    color: '&c'
  amount: 10

xp-progress-style-2:
  xp:
    symbol: \u007c
    color: '&2'
  none:
    symbol: \u007c
    color: '&c'
  amount: 20

multiplier:
  format: HH' hours 'mm' minutes 'ss' seconds'
  zone: Asia/Ho_Chi_Minh

time:
  format: HH.mm.ss
  zone: Asia/Ho_Chi_Minh

date:
  format: dd.MM.yyyy
  zone: Asia/Ho_Chi_Minh