#                                         #
#                levels                #
#                   by                    #
#                MathiasMC                #
#  Any ideas for the plugin or need help? #
#           contact me on spigot          #
#                                         #

# Debug/information messages in console
debug:
  database: false
  save: false
  purge: false

# Database settings
mysql:
  use: false
  host: localhost
  port: 3306
  database: database
  username: username
  password: password

load-players:
  # Load all players into cache on startup?
  all: true

  # Load all online players if not in cache?
  reload: true

unload-players:
  # unload the player from cache on quit?
  quit: false

save:
  use: true

  # How often to save? Seconds.
  interval: 60

levelup:
  # Clear xp on levelup?
  xp-clear: true

  # List of players that will not get xp
  all-excluded:
    - uuid

# You can disable events here.
events:
  Kills: true
  Deaths:
    use: true
    only-players: true

# This section is used then you use /levels generate <levels> as console
generate:
  # Disable command for accidentally typing the command
  disable: false

  # Commands to add per level
  commands:
    - levels message {levels_player} &7[&blevels&7] &eYou are now level {levels_level_to}

  xp:
    # always add that amount
    static: 120

    # + random between min and max
    min: 50
    max: 400

  random:
    use: true
    commands:
      - give {levels_player} diamond
      - give {levels_player} emerald
      - give {levels_player} gold
      - give {levels_player} iron
      - give {levels_player} coal

    # random add to a level between min and max
    min: 1
    max: 35

placeholders:
  # Add levels placeholders to PlaceholderAPI?
  PlaceholderAPI: true

  # Can be obtained using placeholders levels_prefix
  prefix:
    default:
      permission: levels.prefix.default
      list:
        '0': '&e[&7Default&e] &f[&a{levels_level}&f] &e[&7{levels_group}&e]'
      none: '&e[&6Default&e] &f[&a{levels_level}&f] &e[&7{levels_group}&e]'
    vip:
      permission: levels.group.vip
      list:
        '0': '&e[&7VIP&e] &f[&a{levels_level}&f] &e[&7{levels_group}&e]'
      none: '&e[&6VIP&e] &f[&a{levels_level}&f] &e[&7{levels_group}&e]'

  global-booster:
    none: '&cNone'
    name: '&cNone'
    time: '&cNone'
    time-left: '&cNone'
    time-prefix: '&cNone'
    time-left-prefix: '&cNone'

  personal-booster:
    none: '&cNone'
    time: '&cNone'
    time-left: '&cNone'
    time-prefix: '&cNone'
    time-left-prefix: '&cNone'

  # Can be obtained using placeholders levels_date and levels_time
  time:
    format: HH.mm.ss
    zone: Europe/Copenhagen
  date:
    format: dd.MM.yyyy
    zone: Europe/Copenhagen

# This is the max level you can get this must not be higher than the levels in levels.yml
# it takes the first one you have permission to
level-max:
  default:
    permission: levels.max.level.default
    max: 10

# This is used by /pvptop, top 10 placeholders
pvptop:
  xp:
    name: '&cNone'
    value: '&cNone'
    excluded:
      - uuid
  level:
    name: '&cNone'
    value: '&cNone'
    excluded:
      - uuid

# Disable xp from spawners?
spawners:
  xp:
    - zombie
    - skeleton

# Placeholder levels_xp_progress_style
xp-progress-style:
  xp:
    symbol: \u2586
    color: '&2'
  none:
    symbol: \u2588
    color: '&c'
  amount: 10

# Can be obtained using placeholders levels_group and levels_group_to
groups:
  list:
    default:
      permission: levels.group.default
      list:
        '0': Noob
        '1': Bad
        '2': Better
        '3': Good
        '4': Pro
        '5': Super
      none: None
  none: None

# Stop players from farming xp from killing the same player
kill-session:
  use: false

  # Amount of times a player must kill another player to get in the kill session
  amount: 4

  # Amount of time (in seconds) a player is in the kill session
  time: 150

  commands:
    get:
      - levels message {levels_player} &7[&blevels&7] &eYou have been put in
        a kill session for killing {levels_killed} {levels_amount} times
    abuse:
      - kick {levels_player} You cannot kill the same player so many times
    remove:
      - levels message {levels_player} &7[&blevels&7] &eYou have been removed
        from the kill session

# entityName:
#   permissionGroup:
#     name: customEntityName
#     min: 2
#     max: 4
#     permission: levels.mypermission
#     worlds:
#       - world
#     commands: []
#
# if level is not found commands is the default
#
#     level-commands:
#       1:
#       - cmd1
#       2:
#       - cmd2
#     xp-lose:
#       min: 5
#       max: 20
#       commands:
#         level: []
#         lose: []
#
xp:
  player:
    default:
      name: '{levels_player}'
      min: 3
      max: 8
      permission: levels.xp.player.default
      worlds:
        - world
      commands:
        - levels message {levels_player} &7[&blevels&7] &c{levels_type}
          &e+&6{levels_xp_get} &eXP &6{levels_xp_needed} &eto level &c{levels_level_to}
          {levels_booster_global_prefix} {levels_booster_personal_prefix}
kills:
  # Worlds where you can get kills
  worlds:
    - world

  default:
    delay: 0
    permission: levels.kill.commands
    worlds:
      - world
    commands:
      - levels message {levels_player} &7[&blevels&7] &e+1 kill
deaths:
  # Worlds where you can get deaths
  worlds:
    - world

  default:
    delay: 0
    permission: levels.death.commands
    worlds:
      - world
    commands:
      - levels message {levels_player} &7[&blevels&7] &e+1 death